const mongoose = require("mongoose");

const CarSchema = new mongoose.Schema(
	{
		title: {},
		makeId: {},
		modelId: {},
		images: {},
		realModel: {},
		homeTestDrive: {},
		price: {},
		priceUnit: {},
		transferTax: {},
		makeYear: {},
		registerYear: {},
		fuel: {},
		kmDriven: {},
		transmission: {},
		numberOfOwner: {},
		insuranceValidity: {},
		insuranceType: {},
		rto: {},
		location: {},
		mileage: {},
		groundClearance: {},
		seatingCapacity: {},
		bootSpace: {},
		numberOfSeatingRows: {},
		fuelTankCapacity: {},
		alloyWheels: {},
		frontTyreSize: {},
		spareWheel: {},
		numberOfDoors: {},
		drivetrain: {},
		gearBox: {},
		numberOfGears: {},
		displacement: {},
		numberOfCylinders: {},
		valve: {},
		limitedSlipDifferential: {},
		mildHybrid: {},
		turboCharger: {},
		clutchType: {},
		topSpeed: {},
		maxPower: {},
		maxTorque: {},
		sportMode: {},
		multiDriverMode: {},
		suspensionFrontType: {},
		suspensionRearType: {},
		steeringAdjustmentType: {},
		frontBreakType: {},
		rearBreakType: {},
		steeringType: {},
		minimumTurningRadius: {},
	},
	{
		timestamps: {
			createdAt: "created_at",
			updatedAt: "updated_at",
		},
	}
);

module.exports = mongoose.model("cars", CarSchema);
